### ISSUE TITLE
ss-server crashed.

### ISSUE THREAD

**Issue by sh4run** [sh4run/ss#2]
ss-server crashed with: 

```
(gdb) bt
#0  __strncpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S:297
#1  0x000055cedd9fde6c in strncpy (__len=55, __src=<optimized out>, __dest=0x55cede0c9110 "")
    at /usr/include/x86_64-linux-gnu/bits/string_fortified.h:95
#2  accept_cb (loop=0x7f835b0ae720, w=0x7ffee6557f00, revents=<optimized out>) at server.c:2034
#3  0x00007f835b0a2773 in ev_invoke_pending () from /lib/x86_64-linux-gnu/libev.so.4
#4  0x00007f835b0a6041 in ev_run () from /lib/x86_64-linux-gnu/libev.so.4
#5  0x000055cedd9f7f74 in main (argc=<optimized out>, argv=<optimized out>) at server.c:2678
```

**Comment by sh4run** [comment]
fixed by commit 5a69a1e
